ml-explore/mlx-swift

Source/MLX/Documentation.docc/install.md

Fix minor typo in install.md

---

.circleci/config.yml

Add a step to run pre-commit checks (swift-format) -- this will be helpful for PR builds to make sure we keep everything consistent.

add pre-commit checks (swift-format) to test builds

---

Tests/MLXTests/IntegrationTests.swift

Fix test target warnings

---

Source/MLX/Documentation.docc/examples.md
tools/build-documentation.sh

- reference https://github.com/ml-explore/mlx-swift-examples
- use the github repo to provide a zip file

point to mlx-swift-examples

---

.circleci/config.yml
.pre-commit-config.yaml
vendor/json/CMakeLists.txt

- circleci check to make sure it keeps building
- pre-commit for cmake formatting

cmake support

---

Source/MLX/Documentation.docc/Organization/arithmetic.md
Source/MLX/Documentation.docc/Organization/logical.md
Source/MLX/Documentation.docc/Organization/shapes.md
Source/MLX/MLXArray+Ops.swift
Source/MLX/Ops.swift

- https://github.com/ml-explore/mlx/compare/v0.0.6...v0.0.10
- divmod, inner, outer, tensordot
- isNaN, isInf, isNegativeInf, isPositiveInf
- logicalAnd, logicalOr
- tiled
See also #24

add changes from mlx 0.0.6 to 0.0.10 -- fix for #29

---

README.md
Source/MLX/Documentation.docc/examples.md
Source/MLXNN/Pooling.swift

- Update docs for examples
- Remove stray print in pooling

Docs update for https://github.com/ml-explore/mlx-swift-examples/pull/12

---

.circleci/config.yml
CMakeLists.txt
Source/Cmlx/mlx-generated/common_compiled_preamble.cpp
Source/Cmlx/mlx-generated/metal_compiled_preamble.cpp
Source/MLX/Documentation.docc/Articles/compilation.md
Source/MLX/Documentation.docc/Articles/running-on-ios.md
Source/MLX/Documentation.docc/Organization/arithmetic.md
Source/MLX/Documentation.docc/Organization/convolution.md
Source/MLX/Documentation.docc/Organization/shapes.md
Source/MLX/GPU.swift
Source/MLX/Ops.swift
Source/MLX/Protocols.swift
Source/MLX/Stream.swift
Source/MLX/Transforms+Compile.swift
Source/MLXNN/Activations.swift
tools/update-mlx.sh

- https://github.com/ml-explore/mlx/compare/v0.3.0...v0.5.0
- add atLeast[123]D()
- add convGeneral()
- rename parameter on tensortdot (breaking change)
- add shapeless parameter on compile()
- compile activations by default
~~Note: waiting for updated mlx-c (@andresy) for memory APIs before we take this.~~

adopt mlx API up to 0.5.0

---

README.md
Source/Examples/Tutorial.swift
Source/MLX/DType.swift
Source/MLX/Documentation.docc/Articles/running-on-ios.md
Source/MLX/Documentation.docc/MLX.md
Source/MLX/GPU.swift
Source/MLX/MLXArray+Init.swift
Source/MLX/Ops.swift
Source/MLX/Protocols.swift

- add info about building command line via xcodebuild
- improve documentation that looked sparse -- more examples, explanatory text

documentation updates

---

.spi.yml
CMakeLists.txt
MAINTENANCE.md
Package.swift
Source/MLX/Documentation.docc/MLX.md
Source/MLXFFT/Documentation.docc/MLXFFT.md
Source/MLXFast/Documentation.docc/MLXFast.md
Source/MLXFast/MLXFast.swift
Source/MLXNN/Documentation.docc/MLXNN.md
Source/MLXNN/PositionalEncoding.swift
Source/MLXOptimizers/Documentation.docc/MLXOptimizers.md
Source/MLXRandom/Documentation.docc/MLXRandom.md

- https://github.com/ml-explore/mlx/compare/v0.5.1...v0.6.0
- add MLXFast package
- expose RoPE and scaledDotProductAttention

adopt mlx changes up to v0.6.0

---

Source/MLX/Documentation.docc/Articles/converting-python.md
Tests/MLXTests/MLXArray+IndexingTests.swift

Documentation for cases like https://github.com/ml-explore/mlx-swift/issues/50

add documentation on [::-1]

---

Tests/MLXTests/SaveTests.swift

This follows the recommendation given here:
https://github.com/ml-explore/mlx-swift/pull/60#pullrequestreview-1974116167
I also tried re-introducing the original issue, and ensured that the test fails.

Add integration test for MLX.save(arrays:

---

Tests/MLXTests/SaveTests.swift

- circleci failed (silently?) on the PR run for #61

run swift-format

---

CMakeLists.txt
Source/MLX/Ops.swift
Source/MLX/Transforms+Compile.swift

- this doesn't include any new API (coming later)
- includes two fixes important for smaller stack sizes (e.g. running on a async thread)
- https://github.com/ml-explore/mlx/pull/980
- https://github.com/ml-explore/mlx/pull/982

update to pix up mlx v0.10.0

---

CMakeLists.txt
Package.swift
Source/Cmlx/mlx-generated/common_compiled_preamble.cpp
Source/Cmlx/mlx-generated/metal_compiled_preamble.cpp
Source/MLX/Documentation.docc/Articles/converting-python.md
Source/MLX/Documentation.docc/Organization/arithmetic.md
Source/MLX/Documentation.docc/Organization/indexes.md
Source/MLX/Documentation.docc/Organization/initialization.md
Source/MLX/Documentation.docc/Organization/sorting.md
Source/MLX/Documentation.docc/free-functions.md
Source/MLX/GPU.swift
Source/MLX/MLXArray+Indexing.swift
Source/MLX/MLXArray.swift
Source/MLX/Ops+Array.swift
Source/MLX/Ops.swift
Source/MLX/Stream.swift
Source/MLX/Transforms+Compile.swift
Source/MLX/Transforms+Eval.swift
Source/MLXNN/Activations.swift
Source/MLXNN/Documentation.docc/MLXNN.md
Source/MLXNN/Documentation.docc/activations.md
Source/MLXNN/Linear.swift
Source/MLXNN/Recurrent.swift
Source/MLXNN/Transformer.swift
vendor/metal-cpp.patch
vendor/metal-cpp/Metal/MTLEvent.hpp
vendor/metal-cpp/Metal/MTLHeaderBridge.hpp

- update to v0.12.0
This still needs:
- https://github.com/ml-explore/mlx-c/pull/20
- update the mlx-c submodule
- update the CMake build

update for mlx v0.12.0

---

Source/MLX/Documentation.docc/Articles/converting-python.md
Source/MLX/MLXArray+Ops.swift
Tests/MLXTests/MLXArray+OpsTests.swift

In-place operators

---

Source/MLX/DType.swift
Source/MLX/Device.swift
Source/MLX/GPU.swift
Source/MLX/MLXArray+Indexing.swift
Source/MLX/Nested.swift
Source/MLX/Ops.swift
Source/MLX/ParameterTypes.swift
Source/MLX/Stream.swift
Source/MLXLinalg/Linalg.swift
Source/MLXNN/Activations.swift
Source/MLXNN/Losses.swift
Source/MLXNN/Module.swift
Source/MLXNN/Upsample.swift

In preparation for swift 6 mark types Sendable where appropriate.  Sendable means:
> A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.
https://developer.apple.com/documentation/swift/sendable

mark things Sendable where appropriate

---

Source/MLX/Device.swift
Source/MLX/Stream.swift
Tests/MLXTests/StreamTests.swift

- and unchecked Sendable -- they are immutable

make DeviceOrStream and related Equatable

---

Source/MLX/GPU.swift
Source/MLX/ParameterTypes.swift

- i think these may have been in another branch when I marked the rest sendable

missed two sendable types

---

Source/MLX/Device.swift
Source/MLX/Documentation.docc/Articles/using-streams.md
Source/MLX/Documentation.docc/free-functions.md
Tests/MLXTests/StreamTests.swift

Should resolve https://github.com/ml-explore/mlx-swift/issues/113

Scope portions of a graph's execution to a particular stream

---

Source/MLXNN/Convolution.swift

This mirrors the Python API which added this in 0.18.x.
[x] Ran formatter
[x] Tests pass

Add the groups parameter to MLXNN.Conv1d

---

Source/Cmlx/mlx-generated/binary_ops.cpp
Source/Cmlx/mlx-generated/softmax.cpp

Adopt the mlx v0.18.1 tag
- this addresses #139

switch to v0.18.1 mlx tag

---

Source/MLX/Ops.swift

nit in doc

---

.circleci/config.yml

update for using swift 5.10

---

Source/MLXNN/Quantized.swift

- see also https://github.com/ml-explore/mlx-swift-examples/issues/291

Add quantize function that can return different parameters per layer

---

README.md
Source/MLX/Documentation.docc/examples.md

Updated the README -- a few pieces were outdated.

update README and examples

---

Source/MLX/Documentation.docc/Articles/compilation.md
Source/MLX/Documentation.docc/Articles/running-on-ios.md
Source/MLXNN/Documentation.docc/training.md

Thought I'd clean these up after reading the docs. Love the work the MLX team is doing!

Fix spelling mistakes in docs
