ml-explore/mlx-swift

Source/MLXNN/Activations.swift
Source/MLXNN/Containers.swift
Source/MLXNN/Convolution.swift
Source/MLXNN/Dropout.swift
Source/MLXNN/Embedding.swift
Source/MLXNN/Linear.swift
Source/MLXNN/Normalization.swift
Source/MLXNN/PositionalEncoding.swift
Source/MLXNN/Quantized.swift
Source/MLXNN/Transformer.swift
Tests/MLXTests/TransformTests.swift

Largish change but very mechanical:
- convert `public class` to `open class` -- this allows classes outside the module to subclass
- e.g. `class LayerNorm(nn.LayerNorm)` from `phi`
- expose the ivars as public in case subclasses want to use them (they are `let` so this is safe)

switch NN classes to be open -- support subclasses outside the module

---

Package.swift

Package uses functions introduced in macOS 13.3, that is reported while building the package. This PR bump the macOS platrorm to macOS 13.3
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/System/Library/Frameworks/vecLib.framework/Headers/cblas_new.h:891:6: note: 'cblas_sgemm' has been marked as being introduced in macOS 13.3 here, but the deployment target is macOS 13.0.0

macOS target 13.3

---

Package.swift

Followup to https://github.com/ml-explore/mlx-swift/pull/21 -- apply swift-format.  Wasn't caught in previous PR as the change to Package.swift was on main in the main repo, not in the fork.

apply swiftformat -- now checked in circleci

---

Source/MLXNN/Activations.swift
Source/MLXNN/Containers.swift
Source/MLXNN/Convolution.swift
Source/MLXNN/Dropout.swift
Source/MLXNN/Embedding.swift
Source/MLXNN/Linear.swift
Source/MLXNN/Normalization.swift
Source/MLXNN/Quantized.swift
Source/MLXNN/Transformer.swift
Source/MLXOptimizers/Optimizers.swift
Tests/MLXTests/SubclassTests.swift

I just discovered that:
```
open class X {
public func y() {
}
}
```
you cannot override `y()` in subclasses -- that needs to be marked as open too.
Per #16 we need the same treatment in MLXOptimizers.  Added compile-only test to make sure these can be subclassed outside the package (which wasn't obvious _inside_ the package!)

follow-on to #7 -- need open callAsFunction to be able to override that, even in open classes

---

.spi.yml
MAINTENANCE.md
Source/MLX/Documentation.docc/MLX.md
Source/MLXFFT/Documentation.docc/MLXFFT.md
Source/MLXLinalg/Documentation.docc/MLXLinalg.md
Source/MLXNN/Documentation.docc/MLXNN.md
Source/MLXOptimizers/Documentation.docc/MLXOptimizers.md
Source/MLXRandom/Documentation.docc/MLXRandom.md

- also replace some absolute links with relative links to fit better into non gh pages sites (for cross package linking)
This should partially address https://github.com/ml-explore/mlx-swift/issues/14

add spi.yml for swift package index

---

CMakeLists.txt
Source/MLX/Cmlx+Util.swift
Source/MLX/Documentation.docc/Articles/lazy-evaluation.md
Source/MLX/Documentation.docc/free-functions.md
Source/MLX/Ops.swift
Tests/MLXTests/IntegrationTests.swift
Tests/MLXTests/TransformTests.swift
Tests/MLXTests/Utils.swift

This adopts the latest mlx-c and moves to mlx v0.3.0
Notable changes:
- `save(arrays:...)` now takes optional metadata
- `loadArraysAndMetadata(...)` is added to also load metadata from e.g. safetensors

adopt latest mlx-c and mlx v0.3.0

---

MAINTENANCE.md
Package.swift
README.md
Source/Cmlx/include/mlx.h
Source/MLX/Documentation.docc/Articles/converting-python.md
Source/MLX/Documentation.docc/MLX.md
Source/MLX/Documentation.docc/Organization/arithmetic.md
Source/MLX/Documentation.docc/Organization/logical.md
Source/MLX/Documentation.docc/free-functions.md
Source/MLX/Documentation.docc/install.md
Source/MLX/MLXArray+Ops.swift
Source/MLX/Ops+Array.swift
Source/MLX/Ops.swift
Source/MLXNN/Linear.swift
Source/MLXNN/PositionalEncoding.swift

- this brings the MLXArray methods and free functions up to parity with mlx v0.3.0
- addmm
- diag
- diagonal
- isclose
- adopts fast.rope in RoPE
- adopts admm in Linear
- update documentation and fix any docs warnings
For comparison: https://github.com/ml-explore/mlx/compare/v0.0.10...v0.3.0

integrate MLXArray functions and free functions up to mlx v0.3.0

---

MAINTENANCE.md
README.md
Source/MLX/Documentation.docc/MLX.md
Source/MLXFFT/Documentation.docc/MLXFFT.md
Source/MLXLinalg/Documentation.docc/MLXLinalg.md
Source/MLXNN/Documentation.docc/MLXNN.md
Source/MLXOptimizers/Documentation.docc/MLXOptimizers.md
Source/MLXRandom/Documentation.docc/MLXRandom.md

- documentation is at https://swiftpackageindex.com/ml-explore/mlx-swift/main/documentation/mlxrandom
- this is built daily
- fix the links between packages for their directory layout

move documentation to swift package index

---

Source/MLX/Documentation.docc/Organization/initialization.md
Source/MLX/MLXArray+Init.swift
Source/MLX/MLXArray.swift
Tests/MLXTests/MLXArray+OpsTests.swift

- allow array + 3 where array is either bfloat16 or complex64
- allow read out with item() and asArray()
I ran into this when trying different LLM models

fix support for bfloat16, complex64

---

MAINTENANCE.md
Source/MLX/Documentation.docc/MLX.md
Source/MLXFFT/Documentation.docc/MLXFFT.md
Source/MLXLinalg/Documentation.docc/MLXLinalg.md
Source/MLXNN/Documentation.docc/MLXNN.md
Source/MLXOptimizers/Documentation.docc/MLXOptimizers.md
Source/MLXRandom/Documentation.docc/MLXRandom.md

- the links need to go from https://swiftpackageindex.com/ml-explore/mlx-swift/main/documentation/mlxrandom
- to https://swiftpackageindex.com/ml-explore/mlx-swift/main/documentation/mlx
- the last path component is basically a filename so we need something like this:
- [MLX](mlx)
- [MLXRandom](mlxrandom)
Note: this won't work if you hit https://swiftpackageindex.com/ml-explore/mlx-swift/main/documentation/mlx/ (trailing slash).  If we run in to problems with this we can try an absolute domain relative path next.

fix for cross-package links in SPI

---

Source/MLX/Documentation.docc/Articles/converting-python.md
Source/MLX/Documentation.docc/Organization/arithmetic.md
Source/MLX/Documentation.docc/Organization/initialization.md
Source/MLX/Documentation.docc/free-functions.md
Source/MLX/Factory.swift
Source/MLX/Ops.swift
Source/MLXNN/Linear.swift

- rename repeat -> repeated (swift consistency), deprecate repeat()
- add variant of Linear initializer with parameter names

changes based on recent feedback

---

Source/MLX/Documentation.docc/Articles/compilation.md

It had an extra `inputs:` parameter label

Improve sample code in compilation documentation

---

Package.swift
Source/Cmlx/mlx-conditional/compiled_conditional.cpp

I just add few lines of code to allow compilation on visionOS

Append visionOS support

---

Source/MLX/Ops.swift

I noticed that the fopen call in `save(arrays` was using read mode, because of which the saving was failing. I changed it to "w" to match the other save methods. I did verify this fixes saving.
Given this is a system call, I wasn't sure how to unit test this. If there are any recommendations, let me know, will be happy to add tests.

Use write mode when calling `save(arrays`

---

Source/MLXNN/Module.swift
Tests/MLXTests/ModuleTests.swift

- just like ParameterInfo should be able to write to it once if nil
- otherwise all updates have to go through API and will fatalError if not
Seen during development of LoRA example.

improved support for @ModuleInfo

---

Source/MLX/Documentation.docc/Articles/converting-python.md
Source/MLX/Documentation.docc/Organization/conversion.md
Source/MLX/Documentation.docc/Organization/shapes.md
Source/MLX/Documentation.docc/free-functions.md
Source/MLX/Documentation.docc/troubleshooting.md
Source/MLX/MLXArray+Ops.swift
Source/MLX/MLXArray.swift
Source/MLX/Ops+Array.swift
Source/MLX/ParameterTypes.swift
Source/MLXNN/Activations.swift
Source/MLXNN/Linear.swift
Source/MLXNN/Module.swift
Source/MLXNN/Normalization.swift
Source/MLXNN/Transformer.swift
Tests/MLXTests/ModuleTests.swift

- make a variant of split that returns a tuple for the parts: 2 case (common)
- and destructuring shape properties (convenience)
- add asData to get access to bytes
- handle properties that hold modules/parameters in tuples
- handle optional parameter and module properties with ModuleInfo/PropertyInfo
- bugfix: GroupNorm was ignoring weight, bias
- bugfix: MultiHeadAttention was not reshaping correctly

Updates in support of stable-diffusion

---

Source/MLXNN/Linear.swift
Source/MLXNN/Module.swift
Source/MLXNN/Quantized.swift

Some more updates to handle the new way subclassing Linear we are doing for LoRA in https://github.com/ml-explore/mlx-swift-examples/pull/46
- the new LoRALinear and QLoraLinear implementations are subclasses of Linear
- these need the same access to their superclass initializer that QuantizedLinear had
- freeze/unfreeze need to be open for subclasses

lora updates part 2

---

Source/MLX/Ops.swift
Tests/MLXTests/SaveTests.swift

- we can't use the FILE * variant of the call as the operation is lazy
- the file is being closed before the read of the data is done

fix #71 -- loading npy file always gives zeros

---

Source/MLX/DType.swift
Source/MLX/Documentation.docc/Articles/lazy-evaluation.md
Source/MLX/Documentation.docc/Organization/arithmetic.md
Source/MLX/Documentation.docc/Organization/reduction.md
Source/MLX/Documentation.docc/free-functions.md
Source/MLX/Nested.swift
Source/MLX/Ops+Array.swift
Source/MLX/Ops.swift
Source/MLX/Transforms+Compile.swift
Source/MLXNN/Activations.swift
Source/MLXNN/Module.swift
Source/MLXNN/Upsample.swift
Source/MLXRandom/Random.swift

- some changes from mlx were skipped as we were just updating what we built against
- this pulls in remaining changes from https://github.com/ml-explore/mlx/compare/v0.8.1...v0.12.1
- with the exception of the bitwise operators: https://github.com/ml-explore/mlx-c/issues/23

reconcile changes between mlx 0.8.1 and 0.12.1

---

Source/MLXOptimizers/Optimizers.swift

During my use of mlx-swift, I found that the optimizer in mlx-swift does not expose the learning rate property, making it impossible to dynamically adjust the learning rate during training. 
I believe this is a significant functionality gap. Therefore, this PR changes all relevant properties of the Optimizer to public.

Make Optimizer parameters public to enable dynamic learning rate

---

Source/MLX/MLXArray+Ops.swift

While working on #91, I noticed that there are several overloaded operators with duplicate implementation code. 
To improve code maintainability and adhere to the DRY (Don't Repeat Yourself) principle, I have refactored these operators to call a unified variant that handles the operation for `(lhs: MLXArray, rhs: MLXArray)`.

Unify operator implementation

---

Source/MLXNN/Embedding.swift
Source/MLXNN/Module.swift
Source/MLXNN/Quantized.swift
Tests/MLXTests/ModuleTests.swift

Part of the fix for https://github.com/ml-explore/mlx-swift-examples/issues/53
Ready!

add quantized embedding

---

Source/MLX/MLXArray.swift
Tests/MLXTests/MLXArrayTests.swift

- fixes #83
- mlx::core::array can have non-contiguous backing
- handle those cases and simplify the readout

handle non-contiguous backing when reading out MLXArray

---

CMakeLists.txt
Package.swift
Source/Cmlx/mlx-generated/hadamard.cpp
Source/MLX/Documentation.docc/free-functions.md
Source/MLX/MLXArray+Ops.swift
Source/MLX/Ops+Array.swift
tools/update-mlx.sh

- https://github.com/ml-explore/mlx/compare/v0.15.2...v0.16.0
- https://github.com/ml-explore/mlx-c/pull/31/files
mlx-c actually matches v0.15.2 but we want the Sequoia crash fixes from v0.16.0

update to pick up mlx v0.16.0

---

Source/MLXNN/Module.swift
Tests/MLXTests/ModuleTests.swift

Added a test highlighting this. 
Right now it changes the dimensionality of the Linear layer itself, whereas I would have expected it to throw under the `verify: .all` mode.
If it is preferred to throw in this scenario, I'm happy to create a PR for the change.

Throw if a module is being updated with a mismatched shape under verify all

---

Source/MLXNN/Activations.swift
Tests/MLXTests/IntegrationTests.swift

- add axis parameter to Softmax, LogSoftmax
- deprecates SoftMax and replaces with Softmax (missed in earlier renaming)

additional cases for #122

---

Source/MLXNN/Activations.swift
Source/MLXNN/Losses.swift
Tests/MLXTests/LossTests.swift

Added support for using class probabilities as targets in `func crossEntropy()` based on the python implementation (https://github.com/ml-explore/mlx/blob/1bdc038bf9b88d91a4f022c23a1bbcaf32a06157/python/mlx/nn/losses.py#L22)
Closes #140

Support using class probabilities as targets in `func crossEntropy()`

---

Source/MLXNN/Activations.swift
Source/MLXNN/Losses.swift

The python API uses `"mean"` as the default loss reduction type (https://github.com/ml-explore/mlx/blob/1bdc038bf9b88d91a4f022c23a1bbcaf32a06157/python/mlx/nn/losses.py#L122).
Closes #141

Change default reduction type of `binaryCrossEntropy` to `mean`

---

Source/MLXNN/Activations.swift
Source/MLXNN/Recurrent.swift

The current implementation initializes `Wh` with shape `(3 * hiddenSize, inputSize)` and `(4 * hiddenSize, inputSize)` for `GRU` and `LSTM`, respectively. However, `Wh` in `GRU` and `LSTM` should be initialized with shape `(3 * hidden_size, hidden_size)` and `(4 * hidden_size, hidden_size)` as shown in the python code ([GRU](https://github.com/ml-explore/mlx/blob/211411faf2a22bb4e2637abe5a5df21c61e33af7/python/mlx/nn/layers/recurrent.py#L137) and [LSTM](https://github.com/ml-explore/mlx/blob/211411faf2a22bb4e2637abe5a5df21c61e33af7/python/mlx/nn/layers/recurrent.py#L246))

fix: Fix wrong Wh shape in GRU and LSTM

---

Source/MLXNN/Activations.swift
Source/MLXNN/Transformer.swift

fix: Fix wrong layer norm used in `TransformerDecoderLayer`

---

Source/Cmlx/mlx-generated/metal/steel/attn/kernels/steel_attention.metal
Tests/MLXTests/MLXFastKernelTests.swift
tools/fix-metal-includes.sh

- steel_attenion.metal (new) was missing from the build

fix #172 -- missing steel_attenion.metal

---

Source/MLXNN/Module.swift
Tests/MLXTests/ModuleTests.swift

When calling `m.update(parameters: ..., verify: .all)` on a module, there is no check that is performed to ensure that all the parameters under `m` have been set. This has bitten me a couple times when porting a model to mlx-swift, and I think it's related to this todo in [Module.swift](https://github.com/ml-explore/mlx-swift/blob/70dbb62128a5a1471a5ab80363430adb33470cab/Source/MLXNN/Module.swift#L385).
This PR adds some support to check also for this. A couple comments:
- Most of the change is in the recursive call to `.apply` where the `.value` can be `.none` for the case where we don't have anything in the parameters but have to go through the modules to check that there is no parameter to be set.
- When handling the `.dictionary` case , the iteration has been changed so that we ensure …

Update check all set

---

Source/MLX/Documentation.docc/free-functions.md
Source/MLX/ErrorHandler.swift

- exposes `setErrorHandler` from mlx-c
- Adds a `fatalErrorHandler` which calls `fatalError`, recording a stack trace and attaching the debugger in Xcode. It would be nice to set this by default in mlx-swift, but I'm not sure if that's possible.
Usage: `setErrorHandler(fatalErrorHandler)`

Add setErrorHandler and fatalErrorHandler

---

Source/MLXNN/PositionalEncoding.swift

fix: Correct wrong defatul value on docs of `SinusoidalPositionalEncoding`

---

Source/MLX/Documentation.docc/Organization/shapes.md
Source/MLX/Ops.swift

Add missing `roll()` function.

add missing roll function

---

Source/MLXNN/Module.swift
Tests/MLXTests/ModuleTests.swift

- do not fail parameter update validation for "invalid" keys (e.g. _freqs)
In particular SuScaledRotaryEmbedding is failing validation on `update(parameters:)` because of a missing `_freqs`:
```swift
public class SuScaledRotaryEmbedding: Module {
let _freqs: MLXArray
public init(
...
) {
...
let exponent =
MLXArray(stride(from: 0, to: dimensions, by: 2)).asType(.float32) / Float(dimensions)
let freqs = MLX.pow(MLXArray(base), exponent)
self._freqs = MLXArray(longFactor).asType(.float32) * freqs
```
`_freqs` isn't really a parameter -- it is not meant to be updated, hence the naming with `_`.

Fix https://github.com/ml-explore/mlx-swift-examples/issues/218

---

Package.swift

`default_primitives.cpp` is no longer in mlx

Remove unneeded exclude in Package.swift

---

Source/MLX/Documentation.docc/Articles/compilation.md
Source/MLX/Documentation.docc/Articles/converting-python.md
Source/MLX/Documentation.docc/Organization/shapes.md
Source/MLX/Documentation.docc/free-functions.md
Source/MLX/FFT.swift
Source/MLX/Factory.swift
Source/MLX/Linalg.swift
Source/MLX/MLXFastKernel.swift
Source/MLX/Protocols.swift
Source/MLX/Transforms+Compile.swift
Source/MLXFast/MLXFastKernel.swift
Source/MLXLinalg/Linalg.swift
Source/MLXNN/Convolution.swift
Source/MLXNN/ConvolutionTransposed.swift
Source/MLXNN/Documentation.docc/MLXNN.md
Source/MLXNN/Documentation.docc/activations.md
Source/MLXNN/Documentation.docc/losses.md
Source/MLXRandom/Random.swift

Per report of `padded()` not linking in the docs.

fix disconnected (moved, new params, etc.) links in documentation

---

Source/MLXNN/Losses.swift

file: `Source/MLXNN/Losses.swift`
```
public func smoothL1Loss(
predictions: MLXArray, targets: MLXArray, beta: Float = 1, reduction: LossReduction = .mean
) -> MLXArray {
precondition(predictions.shape == targets.shape)
let diff = abs(predictions - targets)
let loss = which(diff .< beta, 0.5 * square(diff) / beta, abs(diff) - 0.5 * beta)
return reduction.reduce(loss: loss)
}
```
According to the definition of smooth l1 loss
$$l = 
\begin{cases} 
0.5(x - y)^2 / \beta, & \text{if } |x - y| < \beta \\
|x - y| - 0.5\beta, & \text{otherwise}
\end{cases}$$
```
let diff = predictions - targets
```
should be 
```
let diff = abs(predictions - targets)
```

fix smoothL1Loss

---

Package.swift
Source/MLX/Documentation.docc/Articles/converting-python.md

There is a bug around swift-docc that could not generate symbol links for `-` `-=` `/` `/=`. 
And this was fixed in Swift 5.10 based on https://github.com/apple/swift-docc/issues/808. So this PR adds symbol links for these operators.

Fix document symbol links

---

Source/MLX/GPU.swift

This PR covers two small bugs in the GPU memory limit related functions
When calling `cacheLimit` without having previously set any limit, the function would incorrectly report erroneous values (it would report whatever was the current cache value).
The logic has been fixed to report the actual value.
When calling `memoryLimit`, the value would not get saved to the cached variable, prompting the code to call the C function every time. 
Finally the link to the metal doc has been updated.

Return correct value in memory limit getter functions

---

Source/MLX/DType.swift
Source/MLX/Factory.swift

- fixes #199
- there were inconsistent methods for creating MLXArrays with various patterns using Float.self vs .float32
- add an FInfo struct also in support of dtype
- encountered when porting VLMs

consistent treatment of HasDType (Float.self) vs dtype (.float32)

---

Source/MLX/Random.swift
Source/MLX/State.swift
Tests/MLXTests/MLXRandomTests.swift
Tests/MLXTests/Utils.swift

- allow a Key or a RandomState to be used with Random functions
- users can create RandomState
- users can do withRandomState to scope the use of a RandomState -- useful with multiple threads

various Random improvements

---

Source/MLX/Transforms+Compile.swift

- fixes #225
- although CompiledFunction was marked as unchecked(Sendable) it really wasn't
- guard the state with a lock

CompiledFunction is not thread safe

---

Source/MLX/MLXFast.swift

It looks like the value passed in the `mask_mode` should be the empty string by default.

Fix scaled dot product attention mask argument

---

README.md

This PR updates the `README.md` file to clarify the correct URL for adding the `mlx-swift` package in Xcode.
#247 
Update the README to recommend using the full URL with `.git` suffix:  `https://github.com/ml-explore/mlx-swift.git`
Following the [CONTRIBUTING.md](https://github.com/ml-explore/mlx-swift/blob/main/CONTRIBUTING.md) guidelines:
- Xcode version: 16.4 (16F6)
- Device: MacBook Air 13" M3
- macOS version: 15.5 (24F74)

Update README with correct .git package URL for Xcode

---

Source/MLXNN/Module.swift
Tests/MLXTests/ModuleTests.swift

- Fixed setting a value for an optional child module
- Fixed resetting an optional child module back to `nil`
Consider the following example with an optional child module:
```swift
class Example: Module {
@ModuleInfo(key: "a") var a: Linear = Linear(1, 1)
@ModuleInfo(key: "b") var b: Linear?
}
```
Currently, attempting to update `b` via `update(modules:verify:)` fails:
```swift
let linear = Linear(1, 1)
let update = ModuleChildren(values: ["b": .value(linear)])
try example.update(modules: update, verify: .noUnusedKeys) // Fatal error: Unable to set b on Example(b=nil)
```
The reason is it has double optional value inside:
```
(lldb) po (value, type(of: value))
▿ 2 elements
- .0 : nil
- .1 : Swift.Optional<Swift.Optional<MLXNN.Linear>>
``` 
Comparing to a non-optional child module:
``` …
```

Fix optional module updates

---

Source/MLXNN/Activations.swift
Source/MLXNN/Documentation.docc/MLXNN.md
Source/MLXNN/Documentation.docc/activations.md

- Add `ReLUSquared` & `relu_squared`
- Add `compiledRelu`
Applicable to https://github.com/ml-explore/mlx-swift-examples/pull/331
Reference: 
- https://arxiv.org/abs/2109.08668v2
- https://github.com/huggingface/transformers/blob/d5d007a1a0f0c11a726a54c8f00bd71825f84d02/src/transformers/activations.py#L170-L178
- https://github.com/ml-explore/mlx/pull/2294

Add ReLUSquared Activation Function

---

Package.swift
Source/MLX/GPU.swift

This PR adds comprehensive tvOS support to MLX-Swift by updating the Package.swift manifest and providing architecture compatibility for tvOS devices.
Changes
1. Package.swift: Added .tvOS(.v16) to the list of supported platforms
2. GPU.swift: Added tvOS 17.0 to the availability check for the architecture property
Problem
MLX-Swift currently doesn't support tvOS, preventing developers from bringing
on-device ML capabilities to Apple TV applications. When attempting to use MLX-Swift
in a tvOS project:
- The package doesn't declare tvOS support in its manifest
- Compilation fails due to the architecture property being unavailable on older tvOS
versions
Solution
1. Explicitly declare tvOS v16+ support in Package.swift
2. Add tvOS 17.0 to the #available check since the architecture property …

Add support for tvOS

---

Source/MLXNN/Convolution.swift
Source/MLXNN/Module.swift
Tests/MLXTests/ModuleTests.swift

Fixes #251 
Right now the errors just give the last key and the module that it was being set on. This is hard if e.g. the module is Linear and the model is large -- there are typically a LOT of Linear modules.

add path information for parameter update errors -- great help in debugging

---

Source/MLXNN/Module.swift

Despite being a `throwing` function there are still cases where `Module.update()` will terminate with `fatalError` and thus crash the program, in case where the passed parameters are incompatible with the module's definition.
I think it is better to still `throw` in this case and let the caller decide what to do with this error, especially since there is already a non-throwing version of the function (which uses `try!` and thus crashes on any error) if the caller is not interested by error handling.
This PR proposes that all cases of `fatalError` in `update()` functions be replaced by cases of `UpdateError`. Care has been take so that the error message in the exception is similar to the one which was produced by `fatalError`.

Make `Module.update()` throw instead of crash for incompatible parameters

---

MAINTENANCE.md
Source/MLX/Documentation.docc/MLX.md
Source/MLXNN/Documentation.docc/MLXNN.md
Source/MLXOptimizers/Documentation.docc/MLXOptimizers.md

Currently, the top-level documentation for modules includes an "Other MLX Packages" section with self-links and links to deprecated frameworks.
For example, here's the landing page for [MLXNN](https://swiftpackageindex.com/ml-explore/mlx-swift/main/documentation/mlxnn) as it appears on Swift Package Index:
This PR removes all self-links (e.g. linking to `MLXNN` on the landing page for `MLXNN`) and links to deprecated frameworks. This will help prevent new users from navigating to the docs and being confused about the extent of modules available in the MLX package. This PR also updates `MAINTENANCE.md`, but I'm less confident in that change.

Update links to MLX packages in documentation

---

Source/MLX/MLXArray+Indexing.swift
Source/MLXNN/Module.swift
Tests/MLXTests/ModuleTests.swift

Changes from the update to swift-format 602 (tool moved forward from the source)

swift-format 602

---

Source/MLX/ErrorHandler.swift
Source/MLX/MLXArray.swift

- this will force all fatal errors to go through the swift code rather than the mlx-c code
- and produce a fatalError which will stop in the debugger

ensure that the ErrorHandler is installed
